/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.GerenciadorFinanceiro;
import Controller.GerenciadorFuncionario;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author santi
 */
public class JFFinanceiro extends javax.swing.JFrame {

    /** Creates new form JFFinanceiro */
    public JFFinanceiro() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelFinanceiro = new javax.swing.JLabel();
        PeriodoInicial = new javax.swing.JLabel();
        DiaInicial = new javax.swing.JTextField();
        MesInicial = new javax.swing.JTextField();
        AnoInicial = new javax.swing.JTextField();
        PeriodoFinal = new javax.swing.JLabel();
        DiaFinal = new javax.swing.JTextField();
        MesFinal = new javax.swing.JTextField();
        AnoFinal = new javax.swing.JTextField();
        Atualizar = new javax.swing.JButton();
        ScrollPanefinanceiro = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelFinanceiro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        LabelFinanceiro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelFinanceiro.setText("FINANCEIRO");

        PeriodoInicial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PeriodoInicial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PeriodoInicial.setText("Data inicial:");

        DiaInicial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        DiaInicial.setForeground(new java.awt.Color(102, 102, 102));
        DiaInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiaInicial.setText("Dia");
        DiaInicial.setToolTipText("Selecione o dia");
        DiaInicial.setHighlighter(null);
        DiaInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DiaInicialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DiaInicialFocusLost(evt);
            }
        });
        DiaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaInicialActionPerformed(evt);
            }
        });

        MesInicial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        MesInicial.setForeground(new java.awt.Color(102, 102, 102));
        MesInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MesInicial.setText("Mês");
        MesInicial.setToolTipText("Selecione o mês");
        MesInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MesInicialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MesInicialFocusLost(evt);
            }
        });

        AnoInicial.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AnoInicial.setForeground(new java.awt.Color(102, 102, 102));
        AnoInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnoInicial.setText("Ano");
        AnoInicial.setToolTipText("Selecione o ano");
        AnoInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnoInicialFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AnoInicialFocusLost(evt);
            }
        });
        AnoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoInicialActionPerformed(evt);
            }
        });

        PeriodoFinal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        PeriodoFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PeriodoFinal.setText("Data final:");

        DiaFinal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        DiaFinal.setForeground(new java.awt.Color(102, 102, 102));
        DiaFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiaFinal.setText("Dia");
        DiaFinal.setToolTipText("Selecione o dia");
        DiaFinal.setHighlighter(null);
        DiaFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DiaFinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DiaFinalFocusLost(evt);
            }
        });
        DiaFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaFinalActionPerformed(evt);
            }
        });

        MesFinal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        MesFinal.setForeground(new java.awt.Color(102, 102, 102));
        MesFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MesFinal.setText("Mês");
        MesFinal.setToolTipText("Selecione o mês");
        MesFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MesFinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MesFinalFocusLost(evt);
            }
        });

        AnoFinal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AnoFinal.setForeground(new java.awt.Color(102, 102, 102));
        AnoFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AnoFinal.setText("Ano");
        AnoFinal.setToolTipText("Selecione o ano");
        AnoFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                AnoFinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                AnoFinalFocusLost(evt);
            }
        });
        AnoFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoFinalActionPerformed(evt);
            }
        });

        Atualizar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        Atualizar.setText("Atualizar");
        Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Animais", null, null, null},
                {"Funcionarios", null, null, null},
                {"Lojas", null, null, null},
                {"Visitantes", "", null, null}
            },
            new String [] {
                "Setor", "Ganho", "Despesas", "Lucro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPanefinanceiro.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ScrollPanefinanceiro)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(99, 99, 99))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(LabelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PeriodoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(PeriodoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DiaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MesFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AnoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPanefinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AnoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoInicialActionPerformed

    private void DiaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaInicialActionPerformed

    private void DiaInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaInicialFocusGained
        if(DiaInicial.getText().equals("Dia"))
        {
            DiaInicial.setText("");
            DiaInicial.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_DiaInicialFocusGained

    private void MesInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MesInicialFocusGained
        if(MesInicial.getText().equals("Mês"))
        {
            MesInicial.setText("");
            MesInicial.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_MesInicialFocusGained

    private void AnoInicialFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnoInicialFocusGained
        if(AnoInicial.getText().equals("Ano"))
        {
            AnoInicial.setText("");
            AnoInicial.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_AnoInicialFocusGained

    private void DiaFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaFinalFocusGained
        if(DiaFinal.getText().equals("Dia"))
        {
            DiaFinal.setText("");
            DiaFinal.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_DiaFinalFocusGained

    private void DiaFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiaFinalActionPerformed

    private void MesFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MesFinalFocusGained
        if(MesFinal.getText().equals("Mês"))
        {
            MesFinal.setText("");
            MesFinal.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_MesFinalFocusGained

    private void AnoFinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnoFinalFocusGained
        if(AnoFinal.getText().equals("Ano"))
        {
            AnoFinal.setText("");
            AnoFinal.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_AnoFinalFocusGained

    private void AnoFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoFinalActionPerformed

    private void AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarActionPerformed
        PreencherTabela();
    }//GEN-LAST:event_AtualizarActionPerformed

    private void DiaInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaInicialFocusLost
        if(DiaInicial.getText().isEmpty())
        {
            DiaInicial.setText("Dia");
            DiaInicial.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_DiaInicialFocusLost

    private void MesInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MesInicialFocusLost
        if(MesInicial.getText().isEmpty())
        {
            MesInicial.setText("Mês");
            MesInicial.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_MesInicialFocusLost

    private void AnoInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnoInicialFocusLost
        if(AnoInicial.getText().isEmpty())
        {
            AnoInicial.setText("Ano");
            AnoInicial.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_AnoInicialFocusLost

    private void DiaFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaFinalFocusLost
        if(DiaFinal.getText().isEmpty())
        {
            DiaFinal.setText("Dia");
            DiaFinal.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_DiaFinalFocusLost

    private void MesFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MesFinalFocusLost
        if(MesFinal.getText().isEmpty())
        {
            MesFinal.setText("Mês");
            MesFinal.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_MesFinalFocusLost

    private void AnoFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_AnoFinalFocusLost
        if(AnoFinal.getText().isEmpty())
        {
            AnoFinal.setText("Ano");
            AnoFinal.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_AnoFinalFocusLost

    public void PreencherTabela()
    {
        DefaultTableModel val = (DefaultTableModel) jTable1.getModel();
        //Animais
        val.setValueAt("-", 0, 1);
        val.setValueAt(GerenciadorFinanceiro.custoAnimais(), 0, 2);
        val.setValueAt((-1) * GerenciadorFinanceiro.custoAnimais(), 0, 3);
        
        //Funcionarios
        val.setValueAt("-", 1, 1);
        val.setValueAt(GerenciadorFinanceiro.custoFuncionarios(GerenciadorFuncionario.initialize().getListaFuncionarios()), 1, 2);
        val.setValueAt((-1) * GerenciadorFinanceiro.custoFuncionarios(GerenciadorFuncionario.initialize().getListaFuncionarios()), 1, 3);
        
        //Lojas
        val.setValueAt(GerenciadorFinanceiro.ganhoLojas(), 2, 1);
        val.setValueAt("-", 2, 2);
        val.setValueAt(GerenciadorFinanceiro.ganhoLojas(), 2, 3);

        //Visitantes
        val.setValueAt(GerenciadorFinanceiro.ganhoVisitantes(), 3, 1);
        val.setValueAt("-", 3, 2);
        val.setValueAt(GerenciadorFinanceiro.ganhoVisitantes(), 3, 3);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFFinanceiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFFinanceiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoFinal;
    private javax.swing.JTextField AnoInicial;
    private javax.swing.JButton Atualizar;
    private javax.swing.JTextField DiaFinal;
    private javax.swing.JTextField DiaInicial;
    private javax.swing.JLabel LabelFinanceiro;
    private javax.swing.JTextField MesFinal;
    private javax.swing.JTextField MesInicial;
    private javax.swing.JLabel PeriodoFinal;
    private javax.swing.JLabel PeriodoInicial;
    private javax.swing.JScrollPane ScrollPanefinanceiro;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
