/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GerenciadorVisita;
import Model.Associado;
import Model.Visita;
import Model.Visitante;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Família
 */
public class JFVisitas extends javax.swing.JFrame {

    GerenciadorVisita v;
    
    /**
     * Creates new form JFVisitas
     */
    public JFVisitas() {
        initComponents();
    }
    
    public void setVisible(boolean bool, GerenciadorVisita v){
        this.setVisible(bool);
        this.v = v;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPainelBotoes = new javax.swing.JPanel();
        jlVisitas = new javax.swing.JLabel();
        jbHistorico = new javax.swing.JButton();
        jbVisitantes = new javax.swing.JButton();
        jbAssociados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpParente = new javax.swing.JPanel();
        jpHistorico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHistorico = new javax.swing.JTable();
        jbAdicionarVisita = new javax.swing.JButton();
        jbAtualizarTabela = new javax.swing.JButton();
        jpVisitantes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtVisitantes = new javax.swing.JTable();
        jbAtualizarVisitantes = new javax.swing.JButton();
        jpAssociados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtAssociados = new javax.swing.JTable();
        jbAdicionarAssociado = new javax.swing.JButton();
        jbEditarAssociado = new javax.swing.JButton();
        jbAtualizarAssociados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visitas e Visitantes");

        jpPainelBotoes.setBackground(new java.awt.Color(255, 255, 255));

        jlVisitas.setText("VISITAS");

        jbHistorico.setText("Histórico");
        jbHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHistoricoActionPerformed(evt);
            }
        });

        jbVisitantes.setText("Visitantes");
        jbVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisitantesActionPerformed(evt);
            }
        });

        jbAssociados.setText("Associados");
        jbAssociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAssociadosActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPainelBotoesLayout = new javax.swing.GroupLayout(jpPainelBotoes);
        jpPainelBotoes.setLayout(jpPainelBotoesLayout);
        jpPainelBotoesLayout.setHorizontalGroup(
            jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                .addGroup(jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jlVisitas))
                    .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbHistorico)
                        .addGap(18, 18, 18)
                        .addComponent(jbVisitantes)
                        .addGap(18, 18, 18)
                        .addComponent(jbAssociados)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpPainelBotoesLayout.setVerticalGroup(
            jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlVisitas)
                .addGap(18, 18, 18)
                .addGroup(jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbHistorico)
                    .addComponent(jbVisitantes)
                    .addComponent(jbAssociados)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jpPainelBotoes, java.awt.BorderLayout.PAGE_START);

        jpParente.setLayout(new java.awt.CardLayout());

        jtHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Nome", "Tipo entrada"
            }
        ));
        jScrollPane1.setViewportView(jtHistorico);

        jbAdicionarVisita.setText("Adicionar");
        jbAdicionarVisita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarVisitaActionPerformed(evt);
            }
        });

        jbAtualizarTabela.setText("Atualizar");
        jbAtualizarTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpHistoricoLayout = new javax.swing.GroupLayout(jpHistorico);
        jpHistorico.setLayout(jpHistoricoLayout);
        jpHistoricoLayout.setHorizontalGroup(
            jpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(jpHistoricoLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jbAdicionarVisita)
                .addGap(56, 56, 56)
                .addComponent(jbAtualizarTabela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpHistoricoLayout.setVerticalGroup(
            jpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHistoricoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdicionarVisita)
                    .addComponent(jbAtualizarTabela))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpParente.add(jpHistorico, "card4");

        jtVisitantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "RG", "Nascimento"
            }
        ));
        jScrollPane2.setViewportView(jtVisitantes);

        jbAtualizarVisitantes.setText("Atualizar");
        jbAtualizarVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarVisitantesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpVisitantesLayout = new javax.swing.GroupLayout(jpVisitantes);
        jpVisitantes.setLayout(jpVisitantesLayout);
        jpVisitantesLayout.setHorizontalGroup(
            jpVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(jpVisitantesLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jbAtualizarVisitantes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpVisitantesLayout.setVerticalGroup(
            jpVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVisitantesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbAtualizarVisitantes)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpParente.add(jpVisitantes, "card3");

        jtAssociados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "RG", "Data início"
            }
        ));
        jScrollPane3.setViewportView(jtAssociados);

        jbAdicionarAssociado.setText("Adicionar");
        jbAdicionarAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAdicionarAssociadoActionPerformed(evt);
            }
        });

        jbEditarAssociado.setText("Editar");
        jbEditarAssociado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarAssociadoActionPerformed(evt);
            }
        });

        jbAtualizarAssociados.setText("Atualizar");
        jbAtualizarAssociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAtualizarAssociadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAssociadosLayout = new javax.swing.GroupLayout(jpAssociados);
        jpAssociados.setLayout(jpAssociadosLayout);
        jpAssociadosLayout.setHorizontalGroup(
            jpAssociadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(jpAssociadosLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jbAdicionarAssociado)
                .addGap(47, 47, 47)
                .addComponent(jbEditarAssociado)
                .addGap(46, 46, 46)
                .addComponent(jbAtualizarAssociados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAssociadosLayout.setVerticalGroup(
            jpAssociadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpAssociadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAdicionarAssociado)
                    .addComponent(jbEditarAssociado)
                    .addComponent(jbAtualizarAssociados))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpParente.add(jpAssociados, "card2");

        getContentPane().add(jpParente, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHistoricoActionPerformed
        jpParente.removeAll();
        jpParente.add(jpHistorico);
        jpParente.repaint();
        jpParente.revalidate();
        
        DefaultTableModel val = (DefaultTableModel) jtHistorico.getModel();
        val.setRowCount(0);
        
        for(Visita v : this.v.getVisitas()){
            val.addRow(new String[]{v.getDataString(), v.getVisitante().getPrimeiroNome() + " " + v.getVisitante().getSobrenome(), v.getTipo().toString()});
        }
    }//GEN-LAST:event_jbHistoricoActionPerformed

    private void jbVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisitantesActionPerformed
        jpParente.removeAll();
        jpParente.add(jpVisitantes);
        jpParente.repaint();
        jpParente.revalidate();
        
        DefaultTableModel val = (DefaultTableModel) jtVisitantes.getModel();
        val.setRowCount(0);
        
        for(Visitante v : this.v.getVisitantes()){
            val.addRow(new String[]{v.getPrimeiroNome()+" "+v.getSobrenome(), v.getRg(), v.getDataNascimentoString()});
        }
    }//GEN-LAST:event_jbVisitantesActionPerformed

    private void jbAssociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAssociadosActionPerformed
        jpParente.removeAll();
        jpParente.add(jpAssociados);
        jpParente.repaint();
        jpParente.revalidate();
        
        DefaultTableModel val = (DefaultTableModel) jtAssociados.getModel();
        val.setRowCount(0);
        
        for(Associado a : this.v.getAssociados()){
            val.addRow(new String[]{a.getPrimeiroNome()+" "+a.getSobrenome(), a.getRg(), a.getInicioAssociadoString()});
        }
    }//GEN-LAST:event_jbAssociadosActionPerformed

    private void jbAdicionarVisitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarVisitaActionPerformed
        new JFDigitarRg().setVisible(true);
    }//GEN-LAST:event_jbAdicionarVisitaActionPerformed

    private void jbAtualizarTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarTabelaActionPerformed
        DefaultTableModel val = (DefaultTableModel) jtHistorico.getModel();
        val.setRowCount(0);
        
        for(Visita v : this.v.getVisitas()){
            val.addRow(new String[]{v.getDataString(), v.getVisitante().getPrimeiroNome() + " " + v.getVisitante().getSobrenome(), v.getTipo().toString()});
        }
    }//GEN-LAST:event_jbAtualizarTabelaActionPerformed

    private void jbAtualizarVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarVisitantesActionPerformed
        DefaultTableModel val = (DefaultTableModel) jtVisitantes.getModel();
        val.setRowCount(0);
        
        for(Visitante v : this.v.getVisitantes()){
            val.addRow(new String[]{v.getPrimeiroNome()+" "+v.getSobrenome(), v.getRg(), v.getDataNascimentoString()});
        }
    }//GEN-LAST:event_jbAtualizarVisitantesActionPerformed

    private void jbEditarAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarAssociadoActionPerformed
        String rgSelecionado = jtAssociados.getValueAt(jtAssociados.getSelectedRow(), 1).toString();
        Associado a = this.v.getAssociados().get(this.v.buscarRgAssociado(rgSelecionado));
        new JFEditarAssociado().setVisible(true, a);        
    }//GEN-LAST:event_jbEditarAssociadoActionPerformed

    private void jbAtualizarAssociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAtualizarAssociadosActionPerformed
        DefaultTableModel val = (DefaultTableModel) jtAssociados.getModel();
        val.setRowCount(0);
        
        for(Associado a : this.v.getAssociados()){
            val.addRow(new String[]{a.getPrimeiroNome()+" "+a.getSobrenome(), a.getRg(), a.getInicioAssociadoString()});
        }
    }//GEN-LAST:event_jbAtualizarAssociadosActionPerformed

    private void jbAdicionarAssociadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAdicionarAssociadoActionPerformed
        new JFAdicionarAssociado().setVisible(true);
    }//GEN-LAST:event_jbAdicionarAssociadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVisitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAdicionarAssociado;
    private javax.swing.JButton jbAdicionarVisita;
    private javax.swing.JButton jbAssociados;
    private javax.swing.JButton jbAtualizarAssociados;
    private javax.swing.JButton jbAtualizarTabela;
    private javax.swing.JButton jbAtualizarVisitantes;
    private javax.swing.JButton jbEditarAssociado;
    private javax.swing.JButton jbHistorico;
    private javax.swing.JButton jbVisitantes;
    private javax.swing.JLabel jlVisitas;
    private javax.swing.JPanel jpAssociados;
    private javax.swing.JPanel jpHistorico;
    private javax.swing.JPanel jpPainelBotoes;
    private javax.swing.JPanel jpParente;
    private javax.swing.JPanel jpVisitantes;
    private javax.swing.JTable jtAssociados;
    private javax.swing.JTable jtHistorico;
    private javax.swing.JTable jtVisitantes;
    // End of variables declaration//GEN-END:variables
}
