/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;

/**
 *
 * @author Família
 */
public class JFVisitas extends javax.swing.JFrame {

    /**
     * Creates new form JFVisitas
     */
    public JFVisitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPainelBotoes = new javax.swing.JPanel();
        jlVisitas = new javax.swing.JLabel();
        jbHistorico = new javax.swing.JButton();
        jbVisitantes = new javax.swing.JButton();
        jbAssociados = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jpParente = new javax.swing.JPanel();
        jpHistorico = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jpVisitantes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jpAssociados = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpPainelBotoes.setBackground(new java.awt.Color(255, 255, 255));

        jlVisitas.setText("VISITAS");

        jbHistorico.setText("Histórico");
        jbHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHistoricoActionPerformed(evt);
            }
        });

        jbVisitantes.setText("Visitantes");
        jbVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVisitantesActionPerformed(evt);
            }
        });

        jbAssociados.setText("Associados");
        jbAssociados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAssociadosActionPerformed(evt);
            }
        });

        jButton1.setText("Fechar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPainelBotoesLayout = new javax.swing.GroupLayout(jpPainelBotoes);
        jpPainelBotoes.setLayout(jpPainelBotoesLayout);
        jpPainelBotoesLayout.setHorizontalGroup(
            jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                .addGroup(jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jlVisitas))
                    .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jbHistorico)
                        .addGap(18, 18, 18)
                        .addComponent(jbVisitantes)
                        .addGap(18, 18, 18)
                        .addComponent(jbAssociados)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jpPainelBotoesLayout.setVerticalGroup(
            jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPainelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlVisitas)
                .addGap(18, 18, 18)
                .addGroup(jpPainelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbHistorico)
                    .addComponent(jbVisitantes)
                    .addComponent(jbAssociados)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jpPainelBotoes, java.awt.BorderLayout.PAGE_START);

        jpParente.setLayout(new java.awt.CardLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Data", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setText("Adicionar");

        jButton3.setText("Remover");

        jButton4.setText("Editar");

        javax.swing.GroupLayout jpHistoricoLayout = new javax.swing.GroupLayout(jpHistorico);
        jpHistorico.setLayout(jpHistoricoLayout);
        jpHistoricoLayout.setHorizontalGroup(
            jpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jpHistoricoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(52, 52, 52)
                .addComponent(jButton4)
                .addGap(34, 34, 34))
        );
        jpHistoricoLayout.setVerticalGroup(
            jpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpHistoricoLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpParente.add(jpHistorico, "card4");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Nascimento"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton8.setText("Adicionar");

        jButton9.setText("Remover");

        jButton10.setText("Editar");

        javax.swing.GroupLayout jpVisitantesLayout = new javax.swing.GroupLayout(jpVisitantes);
        jpVisitantes.setLayout(jpVisitantesLayout);
        jpVisitantesLayout.setHorizontalGroup(
            jpVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(jpVisitantesLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton8)
                .addGap(45, 45, 45)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10)
                .addGap(46, 46, 46))
        );
        jpVisitantesLayout.setVerticalGroup(
            jpVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVisitantesLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpParente.add(jpVisitantes, "card3");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "CPF", "Data início"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jButton5.setText("Adicionar");

        jButton6.setText("Remover");

        jButton7.setText("Editar");

        javax.swing.GroupLayout jpAssociadosLayout = new javax.swing.GroupLayout(jpAssociados);
        jpAssociados.setLayout(jpAssociadosLayout);
        jpAssociadosLayout.setHorizontalGroup(
            jpAssociadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
            .addGroup(jpAssociadosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jButton5)
                .addGap(56, 56, 56)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addGap(39, 39, 39))
        );
        jpAssociadosLayout.setVerticalGroup(
            jpAssociadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAssociadosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpAssociadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jpParente.add(jpAssociados, "card2");

        getContentPane().add(jpParente, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jbHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHistoricoActionPerformed
        jpParente.removeAll();
        jpParente.add(jpHistorico);
        jpParente.repaint();
        jpParente.revalidate();
    }//GEN-LAST:event_jbHistoricoActionPerformed

    private void jbVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVisitantesActionPerformed
        jpParente.removeAll();
        jpParente.add(jpVisitantes);
        jpParente.repaint();
        jpParente.revalidate();
    }//GEN-LAST:event_jbVisitantesActionPerformed

    private void jbAssociadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAssociadosActionPerformed
        jpParente.removeAll();
        jpParente.add(jpAssociados);
        jpParente.repaint();
        jpParente.revalidate();
    }//GEN-LAST:event_jbAssociadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFVisitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFVisitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton jbAssociados;
    private javax.swing.JButton jbHistorico;
    private javax.swing.JButton jbVisitantes;
    private javax.swing.JLabel jlVisitas;
    private javax.swing.JPanel jpAssociados;
    private javax.swing.JPanel jpHistorico;
    private javax.swing.JPanel jpPainelBotoes;
    private javax.swing.JPanel jpParente;
    private javax.swing.JPanel jpVisitantes;
    // End of variables declaration//GEN-END:variables
}
